#!/usr/bin/with-contenv bash

echo "**** Setting up openssh ****"
ssh-keygen -A
chown -R abc:abc /etc/ssh/

if [[ ${#SSH_USER_DIRECTORY} -gt 0 ]]; then
  usermod --shell /bin/bash -d "${SSH_USER_DIRECTORY}" --unlock abc
else
  echo "**** openssh mod parameter blank or missing ****"
fi

echo "**** openssh mod set up ****"