#!/usr/bin/with-contenv bash

echo "**** Setting up openssh ****"
ssh-keygen -A
chown -R abc:abc /etc/ssh/

if [[ ${#SSH_USER_DIRECTORY} -gt 0 ]] && [[ ${#SSH_USER_PASSWORD} -gt 0 ]]; then
  usermod --shell /bin/bash -d "${SSH_USER_DIRECTORY}" --unlock abc
  echo -n "abc:$SSH_USER_PASSWORD" | chpasswd

  echo "**** openssh mod set up ****"
else
  echo "**** openssh mod parameter blank or missing ****"
fi